'use strict';

goog.provide('Blockly.Msg.factory_ar');

goog.require('Blockly.Msg');

Blockly.Msg.BF_title =  "مصنع اللبنات" ;
Blockly.Msg.BF_preview =  "معاينة - الإتجاه:";
Blockly.Msg.BF_help = "- مستندات : <a href='https://github.com/A-S-T-U-C-E/STudio4Education/wiki' target='blank'> wiki</a> - Merci de partager sur le <a href='https://github.com/A-S-T-U-C-E/STudio4Education/issues' target='blank'> forum</a>";
Blockly.Msg.BF_divBlocks =  "رمز (كود) لرسم الكتلة (\\blocs\\):";
Blockly.Msg.BF_divGenerators =  "كود لمولد (منشئ) Arduino (\\generators\\arduino\\):";
Blockly.Msg.BF_CAT_INPUT = "اتصالات";
Blockly.Msg.BF_CAT_FIELD =  "الحقول";
Blockly.Msg.BF_CAT_FIELD =  "الحقول" ،
Blockly.Msg.BF_CAT_TYPE = "أنواع";
Blockly.Msg.BF_CAT_COLOR =  "الألوان";
Blockly.Msg.BF_alignement_left =  "إلى اليسار";
Blockly.Msg.BF_alignement_right =  "إلى اليمين";
Blockly.Msg.BF_alignement_center =  "في الوسط";
Blockly.Msg.BF_newBlock =  "(الكتلة) إسم دالة اللبنة";
Blockly.Msg.BF_external =  "كتلة خارجية";
Blockly.Msg.BF_internal = "كتلة داخلية";
Blockly.Msg.BF_connect_updown =  "↕ للأعلى والأسفل الإرتباط";
Blockly.Msg.BF_connect_left =  "← الإرتباط إلى اليسار" ;
Blockly.Msg.BF_connect_no = "لا ارتباط";
Blockly.Msg.BF_connect_up =  "↑ الإرتباط إلى الأعلى";
Blockly.Msg.BF_connect_down =  "↓ الإرتباط إلى الأسفل" ;
Blockly.Msg.BF_color = "اللون";
Blockly.Msg.BF_input_alignement =  "حقل محاذي";
Blockly.Msg.BF_input_value_type = "من نوع";
Blockly.Msg.BF_input_value_name =  "اسم";
Blockly.Msg.BF_input_value_title =  "كتلة (لبنة)";
Blockly.Msg.BF_input_statement_title =  "(إعلان) إقرار" ;
Blockly.Msg.BF_input_dummy_title =  "إدخال";
Blockly.Msg.BF_field_static_title =  "النص";
Blockly.Msg.BF_field_input_title =  "حقل النص";
Blockly.Msg.BF_field_math_title =  "عدد";
Blockly.Msg.BF_field_angle_title =  "زاوية";
Blockly.Msg.BF_field_dropdown_title =  "القائمة المنسدلة";
Blockly.Msg.BF_field_dropdown_title2 =  "المسماة";
Blockly.Msg.BF_field_dropdown_option =  "خيار";
Blockly.Msg.BF_field_dropdown_warning =  "يجب أن تحتوي القائمة المنسدلة على خيار واحد على الأقل.";
Blockly.Msg.BF_field_checkbox_title =  "خانة الاختيار";
Blockly.Msg.BF_field_colour_title =  "اللون";
Blockly.Msg.BF_field_variable_title = "متغير";
Blockly.Msg.BF_field_image_title =  "صورة";
Blockly.Msg.BF_field_image_width = "عرض";
Blockly.Msg.BF_field_image_height =  "الارتفاع";
Blockly.Msg.BF_field_image_alternativtext =  "النص البديل";
Blockly.Msg.BF_field_type_group_title =  "مجموعة :";
Blockly.Msg.BF_field_type_group_title2 = "إضافة أنواع";
Blockly.Msg.BF_field_type_group_item = "نوع";
Blockly.Msg.BF_field_type_group_null = "فارغ";
Blockly.Msg.BF_field_type_boolean =  "ثنائي";
Blockly.Msg.BF_field_type_number =  "عدد";
Blockly.Msg.BF_field_type_text =  "نص";
Blockly.Msg.BF_field_type_list =  "جدول (صفيف)";
Blockly.Msg.BF_field_type_other = "أخرى";
Blockly.Msg.BF_field_name_warning1 =  "يوجد" ;
Blockly.Msg.BF_field_name_warning2 = "كتل\n بهذا الاسم.";
Blockly.Msg.BF_blockType =  "اسم";
Blockly.Msg.BF_blockType_warning =  "اسم الكتلة مكرر بالنوع:";
Blockly.Msg.BF_tooltip =  "" هذه الكتلة مستخدمة لـ ... '";
Blockly.Msg.BF_helpUrl =  "http://www.mon-club-elec.fr/pmwiki_reference_arduino/pmwiki.php?n=Main.ReferenceMaxi";
Blockly.Msg.BF_helpGenerator =  "هام: يجب حذف ما هو غير مفيد" ;
Blockly.Msg.BF_help_includes =  "ضع كود المكتبة هنا" ;
Blockly.Msg.BF_help_variables =  "ضع الكود للمتغيرات العامة هنا" ;
Blockly.Msg.BF_help_definitions =  "ضع رمز (كود) المثيلات هنا" ";
Blockly.Msg.BF_help_functions =  "ضع كود الوظيفة (الدالة) هنا" ;
Blockly.Msg.BF_help_setup =  "ضع كود الإعداد (setup()) هنا" ;
Blockly.Msg.BF_help_loop =  "ضع رمز الحلقة (loop()) هنا" ;