'use strict';

goog.provide('Blockly.Msg.factory_en');

goog.require('Blockly.Msg');

Blockly.Msg.BF_title = "Blocks factory";
Blockly.Msg.BF_preview = "Preview sens:";
Blockly.Msg.BF_help = "- Documentation : <a href='https://github.com/A-S-T-U-C-E/STudio4Education/wiki' target='blank'> wiki</a> - Thanks to share on <a href='https://github.com/A-S-T-U-C-E/STudio4Education/issues' target='blank'> forum</a>";
Blockly.Msg.BF_divBlocks = "Block definition (\\blocs\\):";
Blockly.Msg.BF_divGenerators = "Generator stub (\\generators\\arduino\\):";
Blockly.Msg.BF_CAT_INPUT = "input";
Blockly.Msg.BF_CAT_FIELD = "field";
Blockly.Msg.BF_CAT_TYPE = "type";
Blockly.Msg.BF_CAT_COLOR = "colour";
Blockly.Msg.BF_alignement_left = "left";
Blockly.Msg.BF_alignement_right = "right";
Blockly.Msg.BF_alignement_center = "centre";
Blockly.Msg.BF_newBlock = "name of the block's function";
Blockly.Msg.BF_external = "external block";
Blockly.Msg.BF_internal = "inline block";
Blockly.Msg.BF_connect_updown = "↕ top + bottom connections";
Blockly.Msg.BF_connect_left = "← left output";
Blockly.Msg.BF_connect_no = "no connections";
Blockly.Msg.BF_connect_up = "↑ top connections";
Blockly.Msg.BF_connect_down = "↓ bottom connections";
Blockly.Msg.BF_color = "color";
Blockly.Msg.BF_input_alignement = "fields";
Blockly.Msg.BF_input_value_type = "type";
Blockly.Msg.BF_input_value_name = "name";
Blockly.Msg.BF_input_value_title = "value input";
Blockly.Msg.BF_input_statement_title = "statement input";
Blockly.Msg.BF_input_dummy_title = "dummy input";
Blockly.Msg.BF_field_static_title = "text";
Blockly.Msg.BF_field_input_title = "text";
Blockly.Msg.BF_field_math_title = "numeric input";
Blockly.Msg.BF_field_angle_title = "angle";
Blockly.Msg.BF_field_dropdown_title = "dropdown menu";
Blockly.Msg.BF_field_dropdown_title2 = "name";
Blockly.Msg.BF_field_dropdown_option = "option";
Blockly.Msg.BF_field_dropdown_warning = "Drop down menu must\nhave at least one option.";
Blockly.Msg.BF_field_checkbox_title = "checkbox";
Blockly.Msg.BF_field_colour_title = "color";
Blockly.Msg.BF_field_variable_title = "variable";
Blockly.Msg.BF_field_image_title = "image";
Blockly.Msg.BF_field_image_width = "width";
Blockly.Msg.BF_field_image_height = "height";
Blockly.Msg.BF_field_image_alternativtext = "alt text";
Blockly.Msg.BF_field_type_group_title = "any of";
Blockly.Msg.BF_field_type_group_title2 = "add types";
Blockly.Msg.BF_field_type_group_item = "type";
Blockly.Msg.BF_field_type_group_null = "any";
Blockly.Msg.BF_field_type_boolean = "boolean";
Blockly.Msg.BF_field_type_number = "number";
Blockly.Msg.BF_field_type_text = "string";
Blockly.Msg.BF_field_type_list = "array";
Blockly.Msg.BF_field_type_other = "other";
Blockly.Msg.BF_field_name_warning1 = "There are ";
Blockly.Msg.BF_field_name_warning2 = " input blocks\n with this name.";
Blockly.Msg.BF_blockType = "unnamed";
Blockly.Msg.BF_blockType_warning = "Block name collides with existing property:";
Blockly.Msg.BF_tooltip = "'this blocks helps to...'";
Blockly.Msg.BF_helpUrl = "https://www.arduino.cc/reference/en/";
Blockly.Msg.BF_helpGenerator = "IMPORTANT: delete unneeded lines";
Blockly.Msg.BF_help_includes = "libraries code";
Blockly.Msg.BF_help_variables = "variables";
Blockly.Msg.BF_help_definitions = "instance'";
Blockly.Msg.BF_help_functions = "functions";
Blockly.Msg.BF_help_setup = "arduino code for setup()";
Blockly.Msg.BF_help_loop = "arduino code for loop()";