'use strict';

goog.provide('Blockly.Msg.factory_es');

goog.require('Blockly.Msg');

Blockly.Msg.BF_title = "Creación de bloques";
Blockly.Msg.BF_preview = "Previsualización - sentido :";
Blockly.Msg.BF_help = "- Documentación : <a href='https://github.com/A-S-T-U-C-E/STudio4Education/wiki' target='blank'> wiki</a> - Gracias por compartir en el <a href='https://github.com/A-S-T-U-C-E/STudio4Education/issues' target='blank'> foro</a>";
Blockly.Msg.BF_divBlocks = "Código por dibujar el bloque (\\blocs\\) :";
Blockly.Msg.BF_divGenerators = "Código para el generador Arduino (\\generators\\arduino\\) :";
Blockly.Msg.BF_CAT_INPUT = "Conexiones";
Blockly.Msg.BF_CAT_FIELD = "Campos";
Blockly.Msg.BF_CAT_TYPE = "Tipo";
Blockly.Msg.BF_CAT_COLOR = "Colores";
Blockly.Msg.BF_alignement_left = "A izquierda";
Blockly.Msg.BF_alignement_right = "A derecha";
Blockly.Msg.BF_alignement_center = "Al centro";
Blockly.Msg.BF_newBlock = "Nombre de la función bloque";
Blockly.Msg.BF_external = "Bloque externo";
Blockly.Msg.BF_internal = "Bloque interno";
Blockly.Msg.BF_connect_updown = "↕ Conexiones arriba & abajo";
Blockly.Msg.BF_connect_left = "← Connexión a izquierda";
Blockly.Msg.BF_connect_no = "Sin conexiones";
Blockly.Msg.BF_connect_up = "↑ Conexiones arriba";
Blockly.Msg.BF_connect_down = "↓ Conexiones abajo";
Blockly.Msg.BF_color = "color";
Blockly.Msg.BF_input_alignement = "Campo alineado";
Blockly.Msg.BF_input_value_type = "del tipo";
Blockly.Msg.BF_input_value_name = "Nombre";
Blockly.Msg.BF_input_value_title = "Bloque";
Blockly.Msg.BF_input_statement_title = "Declaración";
Blockly.Msg.BF_input_dummy_title = "Entrada";
Blockly.Msg.BF_field_static_title = "Texto";
Blockly.Msg.BF_field_input_title = "Campo de texto";
Blockly.Msg.BF_field_math_title = "Número";
Blockly.Msg.BF_field_angle_title = "Ángulo";
Blockly.Msg.BF_field_dropdown_title = "Menú desplegable";
Blockly.Msg.BF_field_dropdown_title2 = "Llamado";
Blockly.Msg.BF_field_dropdown_option = "Opción";
Blockly.Msg.BF_field_dropdown_warning = "Un menú desplegable tiene que \ntener al menos una opción.";
Blockly.Msg.BF_field_checkbox_title = "Cuadro de selección";
Blockly.Msg.BF_field_colour_title = "Color";
Blockly.Msg.BF_field_variable_title = "Variable";
Blockly.Msg.BF_field_image_title = "Imagen";
Blockly.Msg.BF_field_image_width = "Anchura";
Blockly.Msg.BF_field_image_height = "Altura";
Blockly.Msg.BF_field_image_alternativtext = "Texto alternativo";
Blockly.Msg.BF_field_type_group_title = "Conjunto :";
Blockly.Msg.BF_field_type_group_title2 = "Añade los tipos";
Blockly.Msg.BF_field_type_group_item = "Tipos";
Blockly.Msg.BF_field_type_group_null = "Ninguno";
Blockly.Msg.BF_field_type_boolean = "Binario";
Blockly.Msg.BF_field_type_number = "Número";
Blockly.Msg.BF_field_type_text = "Texto";
Blockly.Msg.BF_field_type_list = "Tabla";
Blockly.Msg.BF_field_type_other = "Otro";
Blockly.Msg.BF_field_name_warning1 = "Hay ";
Blockly.Msg.BF_field_name_warning2 = "bloques\ncon este nombre.";
Blockly.Msg.BF_blockType = "Nombre";
Blockly.Msg.BF_blockType_warning = "El nombre del bloque coincide con el preexistente : ";
Blockly.Msg.BF_tooltip = "'Este bloque sirve para...'";
Blockly.Msg.BF_helpUrl = "http://www.mon-club-elec.fr/pmwiki_reference_arduino/pmwiki.php?n=Main.ReferenceMaxi";
Blockly.Msg.BF_helpGenerator = "IMPORTANTE : suprime el que no sea útil";
Blockly.Msg.BF_help_includes = "Pon aquí el código de las librerias";
Blockly.Msg.BF_help_variables = "Pon aquí el código de las variables globals";
Blockly.Msg.BF_help_definitions = "Pon aquí el código de las instancias'";
Blockly.Msg.BF_help_functions = "Pon aquí el código de las funciones";
Blockly.Msg.BF_help_setup = "Pon aquí el código del setup()";
Blockly.Msg.BF_help_loop = "Pon aquí el código del loop()";
