'use strict';

goog.provide('Blockly.Msg.factory_fr');

goog.require('Blockly.Msg');

Blockly.Msg.BF_title = "Fabrique à blocs";
Blockly.Msg.BF_preview = "Prévisualisation - sens :";
Blockly.Msg.BF_help = "- Documentation : <a href='https://github.com/A-S-T-U-C-E/STudio4Education/wiki' target='blank'> wiki</a> - Merci de partager sur le <a href='https://github.com/A-S-T-U-C-E/STudio4Education/issues' target='blank'> forum</a>";
Blockly.Msg.BF_divBlocks = "Code pour dessiner le bloc (\\blocs\\) :";
Blockly.Msg.BF_divGenerators = "Code pour le générateur Arduino (\\generators\\arduino\\) :";
Blockly.Msg.BF_CAT_INPUT = "connexions";
Blockly.Msg.BF_CAT_FIELD = "champs";
Blockly.Msg.BF_CAT_TYPE = "types";
Blockly.Msg.BF_CAT_COLOR = "couleurs";
Blockly.Msg.BF_alignement_left = "à gauche";
Blockly.Msg.BF_alignement_right = "à droite";
Blockly.Msg.BF_alignement_center = "au centre";
Blockly.Msg.BF_newBlock = "nouveau de la fonction du bloc";
Blockly.Msg.BF_external = "bloc externe";
Blockly.Msg.BF_internal = "bloc interne";
Blockly.Msg.BF_connect_updown = "↕ accroches haut & bas";
Blockly.Msg.BF_connect_left = "← accroche à gauche";
Blockly.Msg.BF_connect_no = "pas d'accroches";
Blockly.Msg.BF_connect_up = "↑ accroche en haut";
Blockly.Msg.BF_connect_down = "↓ accroche en bas";
Blockly.Msg.BF_color = "couleur";
Blockly.Msg.BF_input_alignement = "champ aligné";
Blockly.Msg.BF_input_value_type = "de type";
Blockly.Msg.BF_input_value_name = "nom";
Blockly.Msg.BF_input_value_title = "bloc";
Blockly.Msg.BF_input_statement_title = "déclaration";
Blockly.Msg.BF_input_dummy_title = "entrée";
Blockly.Msg.BF_field_static_title = "texte";
Blockly.Msg.BF_field_input_title = "champ de texte";
Blockly.Msg.BF_field_math_title = "nombre";
Blockly.Msg.BF_field_angle_title = "angle";
Blockly.Msg.BF_field_dropdown_title = "menu déroulant";
Blockly.Msg.BF_field_dropdown_title2 = "nommé";
Blockly.Msg.BF_field_dropdown_option = "option";
Blockly.Msg.BF_field_dropdown_warning = "Un menu déroulant doit\navoir au moins une option.";
Blockly.Msg.BF_field_checkbox_title = "case à cocher";
Blockly.Msg.BF_field_colour_title = "couleur";
Blockly.Msg.BF_field_variable_title = "variable";
Blockly.Msg.BF_field_image_title = "image";
Blockly.Msg.BF_field_image_width = "largeur";
Blockly.Msg.BF_field_image_height = "hauteur";
Blockly.Msg.BF_field_image_alternativtext = "texte de remplacement";
Blockly.Msg.BF_field_type_group_title = "ensemble :";
Blockly.Msg.BF_field_type_group_title2 = "ajouter des types";
Blockly.Msg.BF_field_type_group_item = "type";
Blockly.Msg.BF_field_type_group_null = "vide";
Blockly.Msg.BF_field_type_boolean = "binaire";
Blockly.Msg.BF_field_type_number = "nombre";
Blockly.Msg.BF_field_type_text = "texte";
Blockly.Msg.BF_field_type_list = "tableau";
Blockly.Msg.BF_field_type_other = "autre";
Blockly.Msg.BF_field_name_warning1 = "Il y a ";
Blockly.Msg.BF_field_name_warning2 = "blocs\navec ce nom.";
Blockly.Msg.BF_blockType = "nom";
Blockly.Msg.BF_blockType_warning = "Le nom du bloc fait doublon avec le type : ";
Blockly.Msg.BF_tooltip = "'ce bloc sert à...'";
Blockly.Msg.BF_helpUrl = "http://www.mon-club-elec.fr/pmwiki_reference_arduino/pmwiki.php?n=Main.ReferenceMaxi";
Blockly.Msg.BF_helpGenerator = "IMPORTANT : supprimer ce qui n'est pas utile";
Blockly.Msg.BF_help_includes = "placer ici le code des bibliothèques";
Blockly.Msg.BF_help_variables = "placer ici le code des variables globales";
Blockly.Msg.BF_help_definitions = "placer ici le code des instances'";
Blockly.Msg.BF_help_functions = "placer ici le code des fonctions";
Blockly.Msg.BF_help_setup = "placer ici le code du setup()";
Blockly.Msg.BF_help_loop = "placer ici le code du loop()";